# Generated by Django 4.2.20 on 2026-05-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammarker',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exammarker',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
