# Generated by Django 4.2.7 on 2026-04-29 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('options', models.JSONField()),
                ('votes', models.JSONField(default=dict)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='cbe_app.notification')),
            ],
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message_attachments/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cbe_app.notification')),
            ],
        ),
    ]
