# Generated by Django 4.2.7 on 2026-04-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
