# Generated by Django 4.2.20 on 2026-05-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0002_exammarker_finalized_at_exammarker_is_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammoderation',
            name='moderated_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
