# Generated by Django 6.0.3 on 2026-03-20 14:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0002_alter_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('EE', 'Exceeding Expectations'), ('ME', 'Meeting Expectations'), ('AE', 'Approaching Expectations'), ('BE', 'Below Expectations')], max_length=2)),
                ('sub_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('points', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['rating', '-sub_level'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compulsory', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_mappings', to='cbe_app.learningarea')),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='cbe_app.gradelevel')),
            ],
            options={
                'unique_together': {('grade_level', 'learning_area')},
            },
        ),
        migrations.CreateModel(
            name='StudentPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, choices=[('EE', 'Exceeding Expectations'), ('ME', 'Meeting Expectations'), ('AE', 'Approaching Expectations'), ('BE', 'Below Expectations')], max_length=2, null=True)),
                ('sub_level', models.IntegerField(blank=True, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('evidence_url', models.CharField(blank=True, max_length=500, null=True)),
                ('evidence_type', models.CharField(blank=True, max_length=50, null=True)),
                ('teacher_comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assessed', 'Assessed'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('assessed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbe_app.academicyear')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_portfolios', to=settings.AUTH_USER_MODEL)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_portfolios', to='cbe_app.competency')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='cbe_app.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbe_app.term')),
            ],
            options={
                'unique_together': {('student', 'competency', 'term', 'academic_year')},
            },
        ),
    ]
