# Generated by Django 4.2.20 on 2026-04-30 22:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0002_messagepoll_messageattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(max_length=200)),
                ('objectives', models.JSONField(default=list)),
                ('activities', models.JSONField(default=list)),
                ('resources', models.JSONField(default=list)),
                ('assessment', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(default=40)),
                ('lesson_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbe_app.gradelevel')),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbe_app.learningoutcome')),
                ('strand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbe_app.strand')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbe_app.learningarea')),
                ('substrand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbe_app.substrand')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='cbe_app.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
