# Generated by Django 6.0.3 on 2026-03-22 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0003_gradelevel_gradingscale_curriculummapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('setting_key', models.CharField(choices=[('MONTHLY_TARGET', 'Monthly Collection Target'), ('YEARLY_TARGET', 'Yearly Collection Target'), ('LATE_FEE_PERCENTAGE', 'Default Late Fee Percentage'), ('MINIMUM_PAYMENT', 'Minimum Payment Amount'), ('DEFAULT_CURRENCY', 'Default Currency')], max_length=50, unique=True)),
                ('setting_value', models.DecimalField(decimal_places=2, default=1000000, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Setting',
                'verbose_name_plural': 'Financial Settings',
                'ordering': ['setting_key'],
            },
        ),
    ]
