# Generated by Django 6.0.3 on 2026-04-04 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0004_financialsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='competency',
            name='core_competencies',
            field=models.JSONField(blank=True, default=list, help_text="List of KICD core competency codes e.g. ['CC01', 'CC02']"),
        ),
        migrations.AddField(
            model_name='competency',
            name='values',
            field=models.JSONField(blank=True, default=list, help_text="List of value codes e.g. ['VAL01', 'VAL03']"),
        ),
        migrations.AddField(
            model_name='staffloan',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Address must be at least 10 characters', regex='.{5,}')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='summativerating',
            name='rating',
            field=models.CharField(choices=[('EE1', 'Exceptional (90-100%)'), ('EE2', 'Very Good (75-89%)'), ('ME1', 'Good (58-74%)'), ('ME2', 'Fair (41-57%)'), ('AE1', 'Needs Improvement (31-40%)'), ('AE2', 'Below Average (21-30%)'), ('BE1', 'Well Below Average (11-20%)'), ('BE2', 'Minimal (1-10%)')], max_length=3),
        ),
        migrations.AlterField(
            model_name='termlysummary',
            name='final_rating',
            field=models.CharField(blank=True, choices=[('EE1', 'Exceptional (90-100%)'), ('EE2', 'Very Good (75-89%)'), ('ME1', 'Good (58-74%)'), ('ME2', 'Fair (41-57%)'), ('AE1', 'Needs Improvement (31-40%)'), ('AE2', 'Below Average (21-30%)'), ('BE1', 'Well Below Average (11-20%)'), ('BE2', 'Minimal (1-10%)')], max_length=3, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('year_code', 'year_name')},
        ),
    ]
