# Generated by Django 6.0.3 on 2026-04-08 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0005_competency_core_competencies_competency_values_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strand',
            options={'ordering': ['learning_area', 'grade_level', 'display_order']},
        ),
        migrations.AlterUniqueTogether(
            name='strand',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='strand',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='cbe_app.gradelevel'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Graduated', 'Graduated'), ('Transferred', 'Transferred'), ('Inactive', 'Inactive'), ('Withdrawn', 'Withdrawn'), ('Suspended', 'Suspended')], default='Active', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='strand',
            unique_together={('learning_area', 'strand_code', 'grade_level')},
        ),
    ]
