# Generated by Django 6.0.3 on 2026-04-11 08:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0006_alter_strand_options_alter_strand_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Administrator'), ('principal', 'Principal'), ('deputy_principal', 'Deputy Principal'), ('director_studies', 'Director of Studies'), ('registrar', 'Registrar'), ('bursar', 'Bursar'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('hr_manager', 'HR Manager'), ('student', 'Student')], max_length=30),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_code', models.CharField(max_length=20, unique=True)),
                ('department_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('department_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('head_of_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to='cbe_app.staff')),
                ('subjects', models.ManyToManyField(blank=True, related_name='departments', to='cbe_app.learningarea')),
            ],
            options={
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentStaffAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('head', 'Head of Department'), ('deputy_head', 'Deputy Head'), ('member', 'Member')], default='member', max_length=20)),
                ('sports_responsibility', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='cbe_app.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_assignments', to='cbe_app.staff')),
                ('teaching_subjects', models.ManyToManyField(blank=True, to='cbe_app.learningarea')),
            ],
            options={
                'unique_together': {('staff', 'department')},
            },
        ),
    ]
