# Generated by Django 6.0.3 on 2026-04-11 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0007_remove_user_department_alter_user_role_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentstaffassignment',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='departmentstaffassignment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
