# Generated by Django 6.0.3 on 2026-04-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0008_departmentstaffassignment_assigned_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='expected_graduation_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stream',
        ),
        migrations.AddField(
            model_name='student',
            name='birth_certificate_no',
            field=models.CharField(blank=True, help_text='Birth certificate number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='knec_number',
            field=models.CharField(blank=True, help_text='KNEC registration number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='upi_number',
            field=models.CharField(blank=True, help_text='Unique Personal Identifier from NEMIS', max_length=50, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['upi_number'], name='cbe_app_stu_upi_num_256bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['knec_number'], name='cbe_app_stu_knec_nu_72e170_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['birth_certificate_no'], name='cbe_app_stu_birth_c_a2071c_idx'),
        ),
    ]
