# Generated by Django 6.0.3 on 2026-04-17 19:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0009_remove_student_current_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreCompetency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('indicators', models.JSONField(blank=True, default=list)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Core Competencies',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('indicators', models.JSONField(blank=True, default=list)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=9)),
                ('is_active', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('domain', models.CharField(choices=[('cognitive', 'Cognitive (Knowledge)'), ('psychomotor', 'Psychomotor (Skills)'), ('affective', 'Affective (Values/Attitudes)')], default='cognitive', max_length=20)),
                ('competencies', models.JSONField(blank=True, default=list, help_text='List of competency codes associated')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['substrand', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='WeightConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sba_weight', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('exam_weight', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='competency',
            index=models.Index(fields=['substrand'], name='cbe_app_com_substra_6dd57b_idx'),
        ),
        migrations.AddIndex(
            model_name='competency',
            index=models.Index(fields=['competency_code'], name='cbe_app_com_compete_9bb57b_idx'),
        ),
        migrations.AddIndex(
            model_name='competency',
            index=models.Index(fields=['is_core_competency'], name='cbe_app_com_is_core_8885ea_idx'),
        ),
        migrations.AddIndex(
            model_name='learningarea',
            index=models.Index(fields=['area_code'], name='cbe_app_lea_area_co_77f89f_idx'),
        ),
        migrations.AddIndex(
            model_name='learningarea',
            index=models.Index(fields=['area_type'], name='cbe_app_lea_area_ty_e803f3_idx'),
        ),
        migrations.AddIndex(
            model_name='learningarea',
            index=models.Index(fields=['is_active'], name='cbe_app_lea_is_acti_79eb09_idx'),
        ),
        migrations.AddIndex(
            model_name='strand',
            index=models.Index(fields=['learning_area'], name='cbe_app_str_learnin_fdf242_idx'),
        ),
        migrations.AddIndex(
            model_name='strand',
            index=models.Index(fields=['grade_level'], name='cbe_app_str_grade_l_bd9365_idx'),
        ),
        migrations.AddIndex(
            model_name='strand',
            index=models.Index(fields=['strand_code'], name='cbe_app_str_strand__9777f5_idx'),
        ),
        migrations.AddIndex(
            model_name='substrand',
            index=models.Index(fields=['strand'], name='cbe_app_sub_strand__daa7f6_idx'),
        ),
        migrations.AddIndex(
            model_name='substrand',
            index=models.Index(fields=['substrand_code'], name='cbe_app_sub_substra_f8157c_idx'),
        ),
        migrations.AddField(
            model_name='curriculumversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_curriculum_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='substrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='cbe_app.substrand'),
        ),
        migrations.AddField(
            model_name='weightconfiguration',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_weight_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weightconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_weight_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='curriculumversion',
            index=models.Index(fields=['academic_year'], name='cbe_app_cur_academi_4632a2_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumversion',
            index=models.Index(fields=['is_active'], name='cbe_app_cur_is_acti_57bf94_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumversion',
            index=models.Index(fields=['is_published'], name='cbe_app_cur_is_publ_2048cb_idx'),
        ),
        migrations.AddIndex(
            model_name='learningoutcome',
            index=models.Index(fields=['substrand'], name='cbe_app_lea_substra_a435f4_idx'),
        ),
        migrations.AddIndex(
            model_name='learningoutcome',
            index=models.Index(fields=['domain'], name='cbe_app_lea_domain_aa4a00_idx'),
        ),
    ]
