# Generated by Django 6.0.3 on 2026-04-17 23:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0010_corecompetency_corevalue_curriculumversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('cba', 'Classroom-Based Assessment (CBA)'), ('sba', 'School-Based Assessment (SBA)'), ('cat', 'Continuous Assessment Test (CAT)'), ('end_term', 'End of Term Exam'), ('mock', 'Mock Exam'), ('kpsea', 'KPSEA (Grade 6)'), ('kjsea', 'KJSEA (Grade 9)'), ('other', 'Other')], max_length=20)),
                ('grade_level', models.CharField(choices=[('pp1', 'Pre-Primary 1'), ('pp2', 'Pre-Primary 2'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9')], max_length=10)),
                ('academic_year', models.IntegerField(default=2026)),
                ('term', models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')], default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=180)),
                ('total_marks', models.IntegerField(default=100)),
                ('passing_marks', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('marking', 'Marking'), ('moderation', 'Moderation'), ('published', 'Published'), ('archived', 'Archived'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('classes', models.JSONField(blank=True, default=list)),
                ('marking_scheme', models.TextField(blank=True, null=True)),
                ('weighting', models.JSONField(blank=True, default=dict)),
                ('room_allocation', models.JSONField(blank=True, default=list)),
                ('invigilators', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamMarker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=100)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='cbe_app.exam')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marking_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamModeration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('moderated_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='cbe_app.exam')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission_type', models.CharField(choices=[('global', 'Global'), ('exam', 'Exam Specific')], default='global', max_length=10)),
                ('school_wide_mark_uploading', models.BooleanField(default=False)),
                ('require_moderation', models.BooleanField(default=True)),
                ('auto_publish', models.BooleanField(default=False)),
                ('grade_level_permissions', models.JSONField(blank=True, default=dict)),
                ('subject_teacher_permissions', models.JSONField(blank=True, default=dict)),
                ('lock_enabled', models.BooleanField(default=False)),
                ('lock_until', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permissions', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='cbe_app.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=100)),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='cbe_app.exam')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_results', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='cbe_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('class_id', models.CharField(blank=True, max_length=50, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='cbe_app.exam')),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_code'], name='cbe_app_exa_exam_co_23114c_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['status'], name='cbe_app_exa_status_0f9f20_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_type'], name='cbe_app_exa_exam_ty_6f2567_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['academic_year', 'term'], name='cbe_app_exa_academi_c27434_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exammarker',
            unique_together={('exam', 'subject', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='exampermission',
            unique_together={('permission_type', 'exam')},
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam', 'student'], name='cbe_app_exa_exam_id_c0026c_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['subject'], name='cbe_app_exa_subject_61f290_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam', 'student', 'subject')},
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['exam', 'date'], name='cbe_app_exa_exam_id_79caf0_idx'),
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['subject'], name='cbe_app_exa_subject_aa9405_idx'),
        ),
    ]
