# Generated by Django 6.0.3 on 2026-04-18 01:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0011_exam_exammarker_exammoderation_exampermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSSDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Teacher Categories',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='staff',
            name='cbe_app_sta_departm_357d3d_idx',
        ),
        migrations.RemoveIndex(
            model_name='staff',
            name='cbe_app_sta_employm_1b2ef4_idx',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='passport_no',
            new_name='teacher_code',
        ),
        migrations.AddField(
            model_name='staff',
            name='admin_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='cbe_app.department'),
        ),
        migrations.AddField(
            model_name='staff',
            name='assigned_grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_teachers', to='cbe_app.gradelevel'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employment_type',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Probation', 'Probation'), ('Part-time', 'Part-time'), ('Intern', 'Intern')], default='Permanent', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='national_id',
            field=models.CharField(default='TEMP00000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='personal_email',
            field=models.EmailField(default='temp@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='personal_phone',
            field=models.CharField(default='071234567', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated'), ('Resigned', 'Resigned')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='jss_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='cbe_app.jssdepartment'),
        ),
        migrations.AddField(
            model_name='staff',
            name='teacher_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='cbe_app.teachercategory'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['staff_id'], name='cbe_app_sta_staff_i_c32d81_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['teacher_code'], name='cbe_app_sta_teacher_4d995e_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['teacher_category'], name='cbe_app_sta_teacher_a2e9c3_idx'),
        ),
        migrations.RemoveField(
            model_name='staff',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='bank_branch',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='basic_salary',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='city',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='confirmation_date',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='country',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='emergency_relation',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='exit_interview_conducted',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='exit_interview_notes',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='job_grade',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='kra_pin',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='nhif_no',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='nssf_no',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='reporting_to',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='salary_currency',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='status_date',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='status_reason',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='temporary_address',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='title',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='university',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='year_of_graduation',
        ),
    ]
