# Generated by Django 6.0.3 on 2026-04-19 16:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0012_jssdepartment_teachercategory_alter_staff_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='conducted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_conducted_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CounselingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_code', models.CharField(max_length=20, unique=True)),
                ('session_type', models.CharField(choices=[('Academic Guidance', 'Academic Guidance'), ('Personal Counseling', 'Personal Counseling'), ('Career Counseling', 'Career Counseling'), ('Crisis Intervention', 'Crisis Intervention'), ('Group Session', 'Group Session')], max_length=30)),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], default='Scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_sessions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to='cbe_app.student')),
            ],
            options={
                'ordering': ['-session_date', '-session_time'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_code', models.CharField(max_length=20, unique=True)),
                ('report_type', models.CharField(choices=[('Daily', 'Daily Summary'), ('Weekly', 'Weekly Analysis'), ('Monthly', 'Monthly Report'), ('Quarterly', 'Quarterly Review'), ('Custom', 'Custom Report')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('Excel', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('includes_charts', models.BooleanField(default=True)),
                ('includes_summary', models.BooleanField(default=True)),
                ('status', models.CharField(default='Completed', max_length=20)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_date'],
            },
        ),
        migrations.CreateModel(
            name='InterventionProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_code', models.CharField(max_length=20, unique=True)),
                ('program_name', models.CharField(max_length=200)),
                ('program_type', models.CharField(choices=[('Behavioral', 'Behavioral'), ('Academic', 'Academic'), ('Social', 'Social'), ('Counseling', 'Counseling')], max_length=20)),
                ('description', models.TextField()),
                ('duration_weeks', models.IntegerField(default=4)),
                ('facilitator', models.CharField(max_length=100)),
                ('max_students', models.IntegerField(default=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suspension_code', models.CharField(max_length=20, unique=True)),
                ('suspension_type', models.CharField(choices=[('In-School', 'In-School Suspension'), ('Out-of-School', 'Out-of-School Suspension')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.IntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Appealed', 'Appealed'), ('Overturned', 'Overturned')], default='Active', max_length=20)),
                ('parent_notified', models.BooleanField(default=False)),
                ('parent_notification_date', models.DateField(blank=True, null=True)),
                ('reentry_meeting_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_suspensions', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to='cbe_app.disciplineincident')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to='cbe_app.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConductRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('term', models.CharField(max_length=20)),
                ('conduct_grade', models.CharField(choices=[('A', 'Excellent'), ('B', 'Good'), ('C', 'Satisfactory'), ('D', 'Needs Improvement'), ('F', 'Poor')], default='C', max_length=1)),
                ('merits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('demerits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_points', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Warning', 'Warning'), ('Probation', 'Probation'), ('Suspension', 'Suspension')], default='Good', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_records', to='cbe_app.student')),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('student', 'academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='InterventionEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Dropped', 'Dropped'), ('On Hold', 'On Hold')], default='Active', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='cbe_app.student')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='cbe_app.interventionprogram')),
            ],
            options={
                'unique_together': {('program', 'student')},
            },
        ),
    ]
