# Generated by Django 6.0.3 on 2026-04-24 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbe_app', '0013_alter_attendancesession_conducted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('otp_type', models.CharField(choices=[('force_logout', 'Force Logout Verification'), ('password_reset', 'Password Reset Verification')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='cbe_app_otp_user_id_7a8df0_idx'), models.Index(fields=['otp_code'], name='cbe_app_otp_otp_cod_a44c8c_idx'), models.Index(fields=['otp_type'], name='cbe_app_otp_otp_typ_1df2f4_idx'), models.Index(fields=['expires_at'], name='cbe_app_otp_expires_a1aa52_idx')],
            },
        ),
    ]
